CREATE DATABASE HotelC4TA
GO

USE HotelC4TA
GO

--Table of Admin 

CREATE TABLE Administrator (
ID INT PRIMARY KEY IDENTITY,
FullName VARCHAR(150) NOT NULL,
Email VARCHAR(255) UNIQUE NOT NULL,
PasswordHashed VARCHAR(255) NOT NULL,
Rol VARCHAR(10) DEFAULT 'Admin',
);

--Table of Receptionist 

CREATE TABLE Receptionist (
ID INT PRIMARY KEY IDENTITY,
FullName VARCHAR(150) NOT NULL,
Email VARCHAR(255) UNIQUE NOT NULL,
PasswordHashed VARCHAR(255) NOT NULL,
Code VARCHAR(5) NOT NULL,
);

--Table of Client

CREATE TABLE Client (
DNI VARCHAR(15) PRIMARY KEY,
FullName VARCHAR(150) NOT NULL,
Email VARCHAR(255) UNIQUE NOT NULL,
Phone VARCHAR(20) NOT NULL
);

--Table of Room 

CREATE TABLE Room (
RoomID INT PRIMARY KEY,
RoomFloor INT NOT NULL,
RoomStatus VARCHAR(20) DEFAULT 'Available',
RoomType VARCHAR(20) NOT NULL,
Capacity INT NOT NULL,
BasePrice DECIMAL(10,2) NOT NULL
);

--Table of Booking

CREATE TABLE Booking (
BookingID INT PRIMARY KEY IDENTITY(9999, 1),
StartDate DATE DEFAULT (GETDATE()),
EndDate DATE NOT NULL,
BookingStatus VARCHAR(20) DEFAULT 'Pending',
EstimatedPrice DECIMAL(10,2) NOT NULL,
ClientDNI VARCHAR(15) NOT NULL,
ReceptionistID INT NOT NULL,
RoomID INT NOT NULL,
FOREIGN KEY (ClientDNI) REFERENCES Client(DNI),
FOREIGN KEY (ReceptionistID) REFERENCES Receptionist(ID),
FOREIGN KEY (RoomID) REFERENCES Room(RoomID)
);

--Table of Bills

CREATE TABLE Bill (
BillID INT PRIMARY KEY IDENTITY (9999, 1),
IssueDate DATE DEFAULT (GETDATE()),
TotalAmount DECIMAL(10,2) NOT NULL,
PdfFile VARBINARY(MAX) NULL,
BookingID INT NOT NULL,
FOREIGN KEY (BookingID) REFERENCES Booking(BookingID)
);

--Table of Payments 

CREATE TABLE Payment (
PaymentID INT PRIMARY KEY IDENTITY (9999, 1),
PaymentDate DATE DEFAULT (GETDATE()),
Amount DECIMAL(10,2) NOT NULL,
PaymentMethod VARCHAR(10) DEFAULT 'Cash',
BillID INT NOT NULL,
FOREIGN KEY(BillID) REFERENCES Bill(BillID)
);
